### PR TITLE
🐛 Fix prevent draft update after draft discard

### PR DESCRIPTION
**Pull request by sreehari-aot**
# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-1895
Issue Type: BUG/ FEATURE

# Changes
Added `SUBMIT` exitType for component unmount, which will prevent the component to update the draft during unmount.

### CODE REVIEW

**Review by abhilash-aot — APPROVED** [review]
Good taught on preventing unwanted Draft update Call, lgtm

**Review by alanraju-aot — APPROVED** [review]
LGTM

**Comment by sreehari-aot** [comment]
> Good taught on preventing unwanted Draft update Call, lgtm. However On Submit error case we may need the draft

It will not affect the draft update since whenever the component unmounts with different exitType, it will trigger the draft update

**Review by abilpraju-aot — APPROVED** [review]
LGTM

**Pull request merged**
