### PR TITLE
🐛  fixed task name overflow

### PR DESCRIPTION
**Pull request by shuhaib-aot**
# Issue Tracking

JIRA:  https://aottech.atlassian.net/browse/FWF-1479
Issue Type: BUG/ FEATURE

# Changes
1. fixes : task name overflow fixed

# How has the change been tested?

# Screenshots (if applicable)
image

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

### CODE REVIEW

**Review by abhilash-aot — APPROVED** [review]

**Comment by abhilash-aot** [comment]
Style Updates

**Review by Bonymol-aot — APPROVED** [review]
LGTM

**Comment by sreehari-aot** [comment]
was thinking something like '[task name ] see more..' for this @shuhaib-aot but this is good enough 👍

**Review by abilpraju-aot — APPROVED** [review]
Text overflow in task page fix

**Pull request merged**
