### PR TITLE
Modeler code cleanup

### PR DESCRIPTION
**Pull request by devin-aot**
# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes
Renamed Modeller to Modeler
Cleaned up code

### CODE REVIEW

**Review by abilpraju-aot — COMMENTED** [review]
@devin-aot please fix conflicts

**Review by sreehari-aot — APPROVED** [review]
Looks good to me. I suggest adding more comments.

**Review by abilpraju-aot — APPROVED** [review]
LGTM

**Review by abhilash-aot — APPROVED** [review]
Modeller Typo Updatesand Modeler Changes

**Pull request merged**
