### PR TITLE
draft delete when form delete

### PR DESCRIPTION
**Pull request by shuhaib-aot**
# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-2079
Issue Type: BUG/ FEATURE

## change 
1. when form delete then will delete the draft too

### CODE REVIEW

**Review by abilpraju-aot — APPROVED** [review]

**Review by sreehari-aot — CHANGES_REQUESTED** [review]
This will execute 2 queries for a single operation but I think you can do this in a single execution,
can u try `delete()` instead of `all()` that way we can make use of bulk delete instead of iterating through each entry for delete.

**Comment by shuhaib-aot** [comment]
> This will execute 2 queries for a single operation but I think you can do this in a single execution, can u try `delete()` instead of `all()` that way we can make use of bulk delete instead of iterating through each entry for delete.

I tried that way but didn't work

**Review by abhilash-aot — APPROVED** [review]

**Comment by abhilash-aot** [comment]
Let me know once the update is done as per Sreehari

**Review by sreehari-aot — APPROVED** [review]
seems like bulk deletion does not support when using join statements.

**Pull request merged**
