### PR TITLE
Adding JWT Mock and Keycloak docker mock

### PR DESCRIPTION
**Pull request by sumesh-aot**
# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

### CODE REVIEW

**Comment by sreehari-aot** [comment]
Hi Sumesh, do we have to make any other changes to test cases since they are failing. Any idea why tests fail with mocking?

**Review by sreehari-aot — APPROVED** [review]
LGTM

**Comment by sumesh-aot** [comment]
> Hi Sumesh, do we have to make any other changes to test cases since they are failing. Any idea why tests fail with mocking?

This is only mocking keycloak and jwt. Tests are failing as bpm mock is not in place which I believe Seethal is working on.

**Comment by sreehari-aot** [comment]
Thanks for the clarification.

**Comment by sreehari-aot** [comment]
Thanks for the clarification.

**Review by abhilash-aot — APPROVED** [review]

**Review by auslin-aot — APPROVED** [review]

**Pull request merged**
