### PR TITLE
Stepper-updates on save.

### PR DESCRIPTION
**Pull request by Josephalexantony-aot**
# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-2639
# Changes
Stepper will update only when save/ next button is clicked.. Cant click on the stepper to move stepper state.

# Screenshots (if applicable)
image

### CODE REVIEW

**Review by shuhaib-aot — CHANGES_REQUESTED** [review]
so if its last step what will happen it will active or not

**Comment by Josephalexantony-aot** [comment]
> so if its last step what will happen it will active or not

Yes all steps will be active coherently. 
The change is the stepper was clickable, so that will allow to move to another step even without saving the form which is currently in editing mode, or the newly created form without adding the name or path and saving it. 
now it cannot be clicked to change the step.

**Review by shuhaib-aot — APPROVED** [review]

**Review by abilpraju-aot — APPROVED** [review]

**Comment by fahad-aot** [comment]
could you please check for contrast errors?

**Comment by Josephalexantony-aot** [comment]
> could you please check for contrast errors?

sure

**Review by fahad-aot — APPROVED** [review]

**Review by abhilash-aot — APPROVED** [review]

**Pull request merged**
