### PR TITLE
Testcases - Move authorizations to python API 

### PR DESCRIPTION
**Pull request by auslin-aot**
# Issue Tracking

JIRA: 
Issue Type: FEATURE
https://aottech.atlassian.net/browse/FWF-1658

# Changes
Testcases for moving authorizations to python API

### CODE REVIEW

**Review by abhilash-aot — APPROVED** [review]
Lgtm

**Review by abhilash-aot — APPROVED** [review]
Authorisation checks for workflow/roles moved to python.

**Review by abilpraju-aot — APPROVED** [review]
LGTM

**Review by SnehaSuresh-aot — APPROVED** [review]
LGTM

**Review by sumesh-aot — APPROVED** [review]

**Review by sreehari-aot — APPROVED** [review]
LGTM!

**Pull request merged**
