### PR TITLE
Added REACT_APP as prefix of ENABLE MODULE envs

### PR DESCRIPTION
**Pull request by shuhaib-aot**
# Issue Tracking

JIRA:  https://aottech.atlassian.net/browse/FWF-2366
Issue Type: BUG/ FEATURE

# Changes
1.  changed craco config optimization because we don't need env file in forms flow web so if we need optimized craco then need to use NODE_ENV == production. 
2. changed ENABLE_MODULE envs changed REACT_APP_******

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

### CODE REVIEW

**Review by abhilash-aot — COMMENTED** [review]
The change may be needed in Nav bar microfrontend code as well to hide menu items @shuhaib-aot have a check

**Review by abhilash-aot — COMMENTED** [review]
Also update for Custom_theme_URL

**Comment by shuhaib-aot** [comment]
> The change may be needed in Nav bar microfrontend code as well to hide menu items @shuhaib-aot have a check.

yes we need that. now there is no check in nav bar

**Comment by shuhaib-aot** [comment]
> Also update for Custom_theme_URL, check this is needed to be a build time variable rather than run time ?

updated

**Review by abhilash-aot — APPROVED** [review]

**Review by abhilash-aot — APPROVED** [review]

**Review by abilpraju-aot — APPROVED** [review]

**Review by fahad-aot — APPROVED** [review]

**Review by AbijithS-aot — APPROVED** [review]

**Pull request merged**
