### PR TITLE
🔨 updated Formio env 

### PR DESCRIPTION
**Pull request by shuhaib-aot**
1. new env variable implemented for FORMIO that is: **FORMIO_CLIENT_UI**. if the variable is true then client can view their UI in client-side else they can't. the default value of this variable is false.

### CODE REVIEW

**Review by abilpraju-aot — APPROVED** [review]
LGTM

**Review by Josephalexantony-aot — APPROVED** [review]

**Review by sreehari-aot — COMMENTED** [review]
@shuhaib-aot is it a build time argument or runtime argument? also should we update here too
https://github.com/shuhaib-aot/forms-flow-ai/blob/formio-env-update/forms-flow-forms/docker-compose.yml ?

**Review by alanraju-aot — APPROVED** [review]
LGTM

**Comment by shuhaib-aot** [comment]
> @shuhaib-aot is it a build time argument or runtime argument? also should we update here too https://github.com/shuhaib-aot/forms-flow-ai/blob/formio-env-update/forms-flow-forms/docker-compose.yml ?

thank you its done now

**Review by abhilash-aot — APPROVED** [review]

**Pull request merged**
