### PR TITLE
data analysis API mocking keycloak service 

### PR DESCRIPTION
**Pull request by seethalelias-aot**
# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-1423
Issue Type: BUG/ FEATURE

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

### CODE REVIEW

**Comment by sreehari-aot** [comment]
missing jwt fixture in conftest.py

**Comment by sumesh-aot** [comment]
@seethalelias-aot you are missing a `jwt` fixture in `conftest.py`

**Review by sreehari-aot — APPROVED** [review]
LGTM

**Review by auslin-aot — APPROVED** [review]

**Comment by sreehari-aot** [comment]
@abhilash-aot is it better to open this PR directly to master and bring back the changes altogether?

**Comment by abhilash-aot** [comment]
Please wait before merge. 

> 

Yes. We can do that. But cut the branch from master and do these changes

**Comment by sreehari-aot** [comment]
closing due to duplicate PR

**Pull request closed without merging**
