### PR TITLE
Web-api endpoint to get the list of users for a role/group by querying keycloak.

### PR DESCRIPTION
**Pull request by auslin-aot**
# Issue Tracking

JIRA: 
Issue Type: FEATURE
https://aottech.atlassian.net/browse/FWF-1746

# Changes
Web-api endpoint to get the list of users for a role/group by querying keycloak.

This endpoint will be used to get the list of users in a group/role while trying to re-assign the task .

# Screenshots
**Group based users**
image

**Client based users**
image

**Search users by first name, last name, email**
image

### CODE REVIEW

**Review by sreehari-aot — APPROVED** [review]
Looks good to me, I would suggest adding more logs to identify the cause since most handlers involve network calls.

**Review by sumesh-aot — APPROVED** [review]
Looks good! Just a question though, what was the reason behind adding the search logic in a separate service class than the keycloak service class ?

**Comment by auslin-aot** [comment]
> Looks good! Just a question though, what was the reason behind adding the search logic in a separate service class than the keycloak service class ?

Since search logic is added externally without directly querying keycloak api, so added in a separate service class.

**Comment by auslin-aot** [comment]
> Looks good to me, I would suggest adding more logs to identify the cause since most handlers involve network calls.

Added some logs. Already most of the keycloak request, response logs are captured in keycloak.py

image

**Review by abhilash-aot — APPROVED** [review]
End point for listing users with respect to a role of user. Example Moving of memberGroup call for reviewers list from Keycloak to python. Lgtm. Please update and keep the api specs with latest changes

**Pull request merged**
