### PR TITLE
add Apache license file

### PR DESCRIPTION
**Pull request by jonathan-longe**
As per Github's recommended best practice, consider adding an Apache license file to the project root.  I believe this allows potential users to search for form solutions that are license under the Apache license.  See:  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository. 

Specifically:

> ### Determining the location of your license
> Most people place their license text in a file named LICENSE.txt (or LICENSE.md or LICENSE.rst) in the root of the repository; 
> [here's an example from Hubot](https://github.com/github/hubot/blob/master/LICENSE.md).
> 
> Some projects include information about their license in their README. For example, a project's README may include a note
> saying "This project is licensed under the terms of the MIT license."
> 
> As a best practice, we encourage you to include the license file with your project.

The text of the license was copied verbatim from the link in the README.md file.

### CODE REVIEW

**Review by sumesh-aot — CHANGES_REQUESTED** [review]
@jonathan-longe The license is on each component, which was created after legal consultation. So please close this PR.

**Comment by jonathan-longe** [comment]
Oops that's my misunderstanding.  Thanks @sumesh-aot for clarifying that each component is licensed separately.  Would you consider changing the text at the bottom of the README file in the project root?  Currently I think it implies that the whole project is licensed under the Apache license.

**Comment by sumesh-aot** [comment]
Yes, if you could please change readme to reflect this

**Comment by jonathan-longe** [comment]
@sumesh-aot apologies again for misunderstanding the license.  I've modified the README as discussed.  Please let me know if you'd like additional changes.

**Review by abhilash-aot — APPROVED** [review]

**Pull request closed without merging**
