### PR TITLE
Automation

### PR DESCRIPTION
**Pull request by athira-aot**
# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

### CODE REVIEW

**Review by abilpraju-aot — APPROVED** [review]

**Review by abhilash-aot — COMMENTED** [review]
folder name we can modify bit more relavant to automation script?

**Comment by sumesh-aot** [comment]
@athira-aot We can create a separate repo for this. This repo would only be for functional modules in formsflow.ai

**Comment by athira-aot** [comment]
> @athira-aot We can create a separate repo for this. This repo would only be for functional modules in formsflow.ai

Sure

**Comment by abhilash-aot** [comment]
Closing this PR as this would be moved to different Repo https://github.com/AOT-Technologies/forms-flow-ai-automation-testing

**Pull request closed without merging**
