### PR TITLE
Feature/fwf 3326 permission matrix designer task submission

### PR DESCRIPTION
**Pull request by Bonymol-aot**
# Issue Tracking

JIRA: 
https://aottech.atlassian.net/browse/FWF-3326
https://aottech.atlassian.net/browse/FWF-3432
https://aottech.atlassian.net/browse/FWF-3434

Issue Type: BUG/ FEATURE

# Changes
* Added permission matrix changes for different components, some more changes are yet to done

# Screenshots (if applicable)

# Notes

# Checklist
- [ ] Updated changelog
- [ ] Added meaningful title for pull request

### CODE REVIEW

**Review by auslin-aot — APPROVED** [review]

**Review by fahad-aot — APPROVED** [review]

**Review by arun-s-aot — CHANGES_REQUESTED** [review]
Please change the implementation from using userRoles.includes(<permission_name>) with the variables from 'permissions' constants as per the call @Bonymol-aot

**Comment by Bonymol-aot** [comment]
> Please change the implementation from using userRoles.includes(<permission_name>) with the variables from 'permissions' constants as per the call @Bonymol-aot



> Please change the implementation from using userRoles.includes(<permission_name>) with the variables from 'permissions' constants as per the call @Bonymol-aot

Will update that

**Review by arun-s-aot — APPROVED** [review]
Merging the PR for now as the new changes can help test the backend tickets. Please do the changes mentioned on last comment and add a new PR once completed @Bonymol-aot

**Comment by Bonymol-aot** [comment]
> Merging the PR for now as the new changes can help test the backend tickets. Please do the changes mentioned on last comment and add a new PR once completed @Bonymol-aot

Yeah sure

**Pull request merged**
