### PR TITLE
updated with user end point for search in service task

### PR DESCRIPTION
**Pull request by abilpraju-aot**
# Issue Tracking
https://aottech.atlassian.net/browse/FWF-1875
JIRA: 
Issue Type: BUG/ FEATURE
image

image

### CODE REVIEW

**Review by abhilash-aot — APPROVED** [review]
Lgtm . Please check backend support

**Comment by abilpraju-aot** [comment]
> Lgtm . Please check backend support

Checked working fine

**Review by auslin-aot — COMMENTED** [review]
LGTM

**Review by sreehari-aot — COMMENTED** [review]
does the backend still support the `like` query @auslin-aot ?

**Comment by auslin-aot** [comment]
> does the backend still support the `like` query @auslin-aot ?

search params used now will support the `like` query.

**Comment by sreehari-aot** [comment]
> > does the backend still support the `like` query @auslin-aot ?
> 
> search params used now will support the `like` query.

Then it would be appropriate to use the same right? The current change will only return results if there is an exact match right? @abilpraju-aot

**Comment by auslin-aot** [comment]
> > > does the backend still support the `like` query @auslin-aot ?
> > 
> > 
> > search params used now will support the `like` query.
> 
> Then it would be appropriate to use the same right? The current change will only return results if there is an exact match right? @abilpraju-aot

no. Using search params as firstName, lastName will support 'like'.

**Comment by sreehari-aot** [comment]
> > > > does the backend still support the `like` query @auslin-aot ?
> > > 
> > > 
> > > search params used now will support the `like` query.
> > 
> > 
> > Then it would be appropriate to use the same right? The current change will only return results if there is an exact match right? @abilpraju-aot
> 
> no. Using search params as firstName, lastName will support 'like'.

👍

**Review by sreehari-aot — APPROVED** [review]
LGTM

**Pull request merged**
